[package]
name = "gdk-pixbuf-loader"
version = "0.0.1"
authors = ["Alberto Ruiz <aruiz@gnome.org>"]
workspace = "../"
edition = "2018"


[dependencies]
librsvg = { path = "../librsvg_crate" }
gdk-pixbuf-sys = "0.9.0"
libc = "0.2"
glib-sys = { version="0.9.1", features=["v2_50"] }